language: java
jdk:
  - oraclejdk8
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean install
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true

