language: java
jdk:
- oraclejdk8
install: true
addons:
  sonarqube:
    organization: indrabasak-github
    token:
      secure: 0lOerUj1cWePLgq1scpl2Gs6xpaLnldIIntf1iYPaRcIwmPqdqyvRRjiHkAAuH0g3euh3F9gxweoQk6HNkmPQi21FuFHBAyy26SNfMT3TCxAeOWiRQLW6yck3XrpI400ck+4fZr6dw2om1b+5U9r1U9HS8Ne4pmv6Ujetb9Y2o9elMhiAZH0jIN97k3XEoSD3T1+OeXBEit4tEGkohXqHFn0piMS4Bu+fZLM+65ozadBitKbbECCrapfbUfp0R3kcgfA3PHnu3wzuZH2HaK8Rpq/4Ws8aP9zHw0WPdR9nUptuJClJymI1+hobzxVkQyRqCFsAzdLXrRAlgTrryvfmp4y8fQKNLNqEtoPuS77TV1Wchl/3DkYPQm9sorbg2kJdS2pFbMUU3IbGtkrBHIZ5sV87h8U1jtJWvnfIF/5v1saUOURmABJApLBENbf4nG1NwmAAjAWfpk7hT+spFv7hbCIv0/sD+kRzrQWY3Aj3DSiM11vOXW4+wP4QUDvkRlb5+0i/o+QBTIXo1gGbDeYKBJRUWY6wvC4F0cY1elhUWkQZaFN+8COO7HWOfxX8ZvORtUJy89oDcEgQJ3MfjXiSRZm1ZG8dQiejnJwTPVNzAKUmgf9jdCY/9u/tsbIXm75MxkWR3wITDVkMAQiu8xRBbhsHaTvv4mFSCCCuNvN6U0=
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true

